### ISSUE TITLE
Air Man Wind & Ladders

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#303] opened 2018-09-13 18:06 UTC
Submitter: Riguor
Air Man's blowing effect will push Mega man whether or not he is holding onto a ladder, holding a ladder does not anchor mega man's x position until he lets go. No other wind in the engine acts this way, if I remember.

**Comment by MightyPrinny** [comment] 2018-09-13 18:10
duplicate of #243

**Closed** 2018-09-13 18:13 UTC
Labels: git-report
