### ISSUE TITLE
LaJaBa despawns immediatrly after respawning

### ISSUE THREAD

**Issue by MegamixEngine** [MegamixEngine/MegamixEngine#393] opened 2018-11-10 06:31 UTC
Submitter: Fungus
I put lajaba on the ground in my level. I playtest level. I walk towards where lajaba should be. He is not there. The script at bottom of game maker window says lajaba was spawned, but was then immediately despawned. Moving forward through level and then backtracking to where lajaba should have been will spawn him successfully.

**Comment by snoruntpyro** [comment] 2018-11-19 21:39
Duplicate of an existing issue.

**Closed by snoruntpyro** 2018-11-19 21:39 UTC
Labels: git-report
